version: "3"
services:
  brickwork-backend:
    build:
      context: "."
      dockerfile: Dockerfile
#    ports:
#      - "5000:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - app_data:/app/data
    depends_on:
    - postgres
    - redis
    command: ["python", "src/main.py"]
#    restart: always

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  app_data:
  postgres_data:
  redis_data: